openapi: "3.0.3"

info:
  title: "Eth2 key manager API"
  description: |
    API specification for a key manager client, which enables users to manage keystores.

    The key manager API is served by the binary holding the validator keys. This binary may be a remote signer or a validator client.

    All routes SHOULD be exposed through a secure channel, such as with HTTPs, an SSH tunnel, a VPN, etc.

    All requests by default send and receive JSON, and as such should have either or both of the "Content-Type: application/json"
    and "Accept: application/json" headers.

    All sensitive routes are to be authenticated with a token. This token should be provided by the user via a secure channel:
      - Log the token to stdout when running the binary with the key manager API enabled
      - Read the token from a file available to the binary
  version: "v1.0.0-alpha"
  contact:
    name: Ethereum Github
    url: https://github.com/ethereum/keymanager-APIs/issues
  license:
    name: "Creative Commons Zero v1.0 Universal"
    url: "https://creativecommons.org/publicdomain/zero/1.0/"

servers:
  - url: "{server_url}"
    variables:
      server_url:
        description: "key manager API url"
        default: "https://public-mainnet-node.ethereum.org"

tags:
  - name: Local Key Manager
    description: Set of endpoints for key management of local keys.
  - name: Remote Key Manager
    description: Set of endpoints for key management of external keys.

paths:
  /eth/v1/keystores:
    $ref:  './apis/local_keystores.yaml'
  /eth/v1/remotekeys:
    $ref:  './apis/remote_keystores.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: URL safe token, optionally JWT

  schemas:
    Pubkey:
      $ref: './types/public_key.yaml'
    Keystore:
      $ref: './types/keystore.yaml'
    SignerDefinition:
      $ref: './types/signer_definition.yaml'
    SlashingProtectionData:
      $ref: './types/slashing_protection.yaml'
    ErrorResponse:
      $ref: './types/error_response.yaml'
    Url:
      $ref: './types/url.yaml'
