name: Deploy

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare deploy directory
        run: |
          mkdir ./deploy
          cp -r dist ./deploy
          cp -r assets ./deploy
          cp -r index.html ./deploy
      - name: Bundle spec
        uses: mpetrunic/swagger-cli-action@v1.0.0
        with:
          command: "bundle ./keymanager-oapi.yaml -r -t yaml -o ./deploy/keymanager-oapi.yaml"
      - name: Publish to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          publish_branch: gh-pages
