name: CI

on:
  push:
    branches:
      - "master"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm i -g @apidevtools/swagger-cli@4 @redocly/cli@1.19.0

      - name: Lint spec
        run: redocly lint ./keymanager-oapi.yaml

      - name: Bundle spec
        run: "swagger-cli bundle ./keymanager-oapi.yaml -r -t yaml -o ./deploy/keymanager-oapi.yaml"
