name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bundle yaml spec
        uses: mpetrunic/swagger-cli-action@v1.0.0
        with:
          command: "bundle ./keymanager-oapi.yaml -r -t yaml -o ./deploy/keymanager-oapi.yaml"
      - name: Bundle json spec
        uses: mpetrunic/swagger-cli-action@v1.0.0
        with:
          command: "bundle ./keymanager-oapi.yaml -r -t json -o ./deploy/keymanager-oapi.json"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Yaml Bundle
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./deploy/keymanager-oapi.yaml
          asset_name: keymanager-oapi.yaml
          asset_content_type: text/x-yaml
      - name: Upload Json Bundle
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./deploy/keymanager-oapi.json
          asset_name: keymanager-oapi.json
          asset_content_type: application/json
      - name: Rollback Release
        if: failure()
        uses: author/action-rollback@stable
        with:
          # Using a known release ID
          id: ${{ steps.create_release.id }}
          # Using a tag name
          tag: ${{ github.ref }}
          # Always delete} the tag, even if a release is not associated with it.
          always_delete_tag: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
